---
apiVersion: v1
kind: Pod
metadata:
  name: httpbin
  labels:
    name: httpbin
spec:
  containers:
  - name: httpbin
    image: kennethreitz/httpbin:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
spec:
  selector:
    app: httpbin
  ports:
  - port: 80
    targetPort: 80
